server:
  port: 8093
spring:
  application.name: payment-service
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/paymentdb}
    username: ${DB_USERNAME:logistics}
    password: ${DB_PASSWORD:logistics}
  jpa:
    hibernate.ddl-auto: ${JPA_DDL_AUTO:update}
    open-in-view: false
  kafka:
    bootstrap-servers: ${KAFKA_BROKER:localhost:9092}
    consumer.group-id: payment-service
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
management:
  endpoints.web.exposure.include: health,info,prometheus
  endpoint.health.probes.enabled: true
