package org.micro.myservice.logistics.event;

public enum LogisticsEventType {
    ORDER_CREATED,
    INVENTORY_RESERVED,
    INVENTORY_RESERVATION_FAILED,
    PAYMENT_APPROVED,
    PAYMENT_FAILED,
    DELIVERY_REQUESTED,
    DELIVERY_REQUEST_FAILED,
    ORDER_CONFIRMED,
    ORDER_CANCELLED,
    INVENTORY_RELEASED,
    PAYMENT_CANCELLED
}
